# 6 Talen voor de training
# Alleen unicode is toegestaan in de talen!

def GetTrainingData():
    training_data = []
    
    # Nederlands
    training_data.append({"class":"Nederlands", "sentence":"De ingewanden van zijn laatste slachtoffer hingen halfstok."})
    training_data.append({"class":"Nederlands", "sentence":"Sam Hudder wierp een controlerende blik omhoog op de vlaggenstok toen hij zijn huisdeur afsloot."})
    training_data.append({"class":"Nederlands", "sentence":"Het grauw glanzende vlees hing er goed bij zichtbaar voor eenieder die passeerde."})
    training_data.append({"class":"Nederlands", "sentence":"Meer dan een kleine creatie was het niet, een vingeroefening."})
    training_data.append({"class":"Nederlands", "sentence":"Gewoontegetrouw zette de kunstenaar zijn kraag op en trok hij zijn hoed voor zijn ogen als bescherming tegen de flitslichten van de fotocamera's."})
    training_data.append({"class":"Nederlands", "sentence":"Hoewel de lucht met loodgrijze wolken was dichtgeslibd, barstte de dag niet in de bliksemschichten van roem los."})
    training_data.append({"class":"Nederlands", "sentence":"De troostelozen die zich over straat spoedden, hadden amper aandacht voor de menselijke restanten aan de vlaggenmast."})
    training_data.append({"class":"Nederlands", "sentence":"Een enkeling knikte hem beleefd toe, keek op naar de darmen en wist dat alles goed was."})
    training_data.append({"class":"Nederlands", "sentence":"Sam Hudder huiverde."})
    training_data.append({"class":"Nederlands", "sentence":"Zo ging het nu al maanden."})
    training_data.append({"class":"Nederlands", "sentence":"Hij kon scherp blijven wat hij wilde en creeren tot hij dood neerviel, voor de buitenwereld was hij overbodig geworden."})
    training_data.append({"class":"Nederlands", "sentence":"Hij had er altijd op vertrouwd dat de visie van een mens de wereld kon veranderen."})
    training_data.append({"class":"Nederlands", "sentence":"Reeds in zijn jonge jaren wist hij dat hij deze taak als een waar profeet op zich zou nemen."})
    training_data.append({"class":"Nederlands", "sentence":"Geboren kunstenaar, de taal waardoor hij voorbestemd was te spreken."})
    training_data.append({"class":"Nederlands", "sentence":"Zijn eerste creatie was een mammoetproject geweest."})
    training_data.append({"class":"Nederlands", "sentence":"Hij had er een half leven aan gewerkt, want een profeet mocht geen half werk leveren."})
    training_data.append({"class":"Nederlands", "sentence":"De eerste stappen op Het Pad waren de belangrijkste."})
    training_data.append({"class":"Nederlands", "sentence":"Critici bejubelden zijn Huis van Botten."})
    training_data.append({"class":"Nederlands", "sentence":"Het publiek had aanvankelijk meer afhoudend gereageerd, maar met zijn volgende creaties had hij het gewone volk ook voor zich gewonnen."})
    training_data.append({"class":"Nederlands", "sentence":"Op ieder continent kende men zijn naam en waren zijn sporen zichtbaar."})
    training_data.append({"class":"Nederlands", "sentence":"Wandtapijten gevlochten haar van de uitverkorenen die door zijn hand waren gevallen, sierden de muren in grote musea."})
    training_data.append({"class":"Nederlands", "sentence":"Mobielen van nagels zongen in elke windstreek hun ingetogen lied."})
    training_data.append({"class":"Nederlands", "sentence":"Rivieren hadden rood gezien van het door hem vergoten bloed."})
    training_data.append({"class":"Nederlands", "sentence":"Hij was de alchemist die de alchemie van het zien voorgoed had veranderd."})
    training_data.append({"class":"Nederlands", "sentence":"Tegenwoordig was onverschillige stilte de enige reactie op zijn werk."})
    training_data.append({"class":"Nederlands", "sentence":"Waar waren de volgelingen die om dood door zijn aanraking smeekten? De jaloerse blikken en wanhoop omdat hij voor een ander koos? En de enkeling die besloot zijn eigen en enige kunstwerk te worden door de hand aan zichzelf te slaan? Zijn demonen waren tegenwoordig niet meer dan schoothondjes."})
    training_data.append({"class":"Nederlands", "sentence":"Niet dat zijn creaties minder gruwelijk waren."})
    training_data.append({"class":"Nederlands", "sentence":"Het was een teken dat in zijn missie was geslaagd de wereld was zo zwart geworden dat zijn werk niet meer opviel."})
    training_data.append({"class":"Nederlands", "sentence":"Voldaan zou hij van zijn nadagen moeten genieten."})
    training_data.append({"class":"Nederlands", "sentence":"Maar dat was niet het geval."})
    training_data.append({"class":"Nederlands", "sentence":"De duisternis vulde hem met gruwel, want alles wat hij deed was plotseling zo alledaags."})
    training_data.append({"class":"Nederlands", "sentence":"Niet minder alledaags was zijn huidige missie, want zelfs een man als Sam Hudder moest eten."})
    training_data.append({"class":"Nederlands", "sentence":"De grauwe straten van de stad bekoorden hem niet."})
    training_data.append({"class":"Nederlands", "sentence":"Ze waren triester dan hij zich ooit had kunnen voorstellen."})
    training_data.append({"class":"Nederlands", "sentence":"Er was niets opmerkelijks aan de steeg die hij op weg naar de supermarkt passeerde een donkere naad die het natte asfalt openspleet."})
    training_data.append({"class":"Nederlands", "sentence":"Niets opmerkelijks, behalve een gerucht."})
    training_data.append({"class":"Nederlands", "sentence":"Waarom hij zijn pas inhield, zou hij zich nooit herinneren."})
    training_data.append({"class":"Nederlands", "sentence":"Het was een kracht groter dan zijn instinct om te scheppen."})
    training_data.append({"class":"Nederlands", "sentence":"Hij liep de steeg in en speurde tussen het vuil naar de oorsprong van de dierlijke geluiden."})
    training_data.append({"class":"Nederlands", "sentence":"Het rook naar urine en moord."})
    training_data.append({"class":"Nederlands", "sentence":"Niemand wist beter hoe moord rook dan Sam Hudder."})
    training_data.append({"class":"Nederlands", "sentence":"Hij zocht echter geen slachtoffer."})
    training_data.append({"class":"Nederlands", "sentence":"Niet vandaag."})
    training_data.append({"class":"Nederlands", "sentence":"Vlees verveelde hem zo."})
    training_data.append({"class":"Nederlands", "sentence":"Vooral willoos vlees."})
    training_data.append({"class":"Nederlands", "sentence":"En toch was het vlees wat hij vond, weggeworpen als vuil."})
    training_data.append({"class":"Nederlands", "sentence":"Koortsachtig warm van het leven, maar vies door stad en afval."})
    training_data.append({"class":"Nederlands", "sentence":"Sam Hudder tilde het mauwende hoopje modder uit de vuilbak, waar het zich wanhopig een weg uit had geprobeerd te klauwen."})
    training_data.append({"class":"Nederlands", "sentence":"Ontzetting maakte zich van hem meester."})
    training_data.append({"class":"Nederlands", "sentence":"Waarom wist hij niet."})
    training_data.append({"class":"Nederlands", "sentence":"Hij bestudeerde zijn emotie, zwolg er even in, en vroeg zich af wat hij ermee aan moest."})
    training_data.append({"class":"Nederlands", "sentence":"Dit gevoel was hem volkomen vreemd."})
    training_data.append({"class":"Nederlands", "sentence":"Toen nam hij zijn sjaal van zijn hals - een van de instrumenten waarmee hij ontelbare keren door middel van wurging had gecreeerd - en veegde het tegenstribbelende diertje zo goed en kwaad als het ging schoon."})
    training_data.append({"class":"Nederlands", "sentence":"Een prachtige, roomwitte vacht werd onthuld."})
    training_data.append({"class":"Nederlands", "sentence":"De kunstenaar trok een van zijn zwarte leren handschoenen uit en kroelde zijn vingers door de pluizige vacht."})
    training_data.append({"class":"Nederlands", "sentence":"Hoe lang was het geleden dat hij iets zonder handschoenen had aangeraakt? Hij bestudeerde het poesje en vroeg zich af hoe hij er een nieuwe creatie van kon maken."})
    training_data.append({"class":"Nederlands", "sentence":"Het was een beroepsdeformatie dat hij alles door de ogen van een schepper bekeek."})
    training_data.append({"class":"Nederlands", "sentence":"Een vreemd gevoel vulde hem bij het vasthouden van het hulpeloze hoopje leven."})
    training_data.append({"class":"Nederlands", "sentence":"Het duurde niet lang of hij wist wat hij ermee moest aanvangen."})
    training_data.append({"class":"Nederlands", "sentence":"Eens te meer zou hij de wereld veranderen."})
    training_data.append({"class":"Nederlands", "sentence":"Hij stopte het jonge dier half onder zijn jas en vervolgde zijn weg naar de supermarkt."})
    training_data.append({"class":"Nederlands", "sentence":"Met een fles melk in de ene en het witte pluizebolletje in de andere hand werd Sam Hudder op de gevoelige plaat vastgelegd."})
    training_data.append({"class":"Nederlands", "sentence":"Hij verschool zijn blik achter de rand van zijn hoed."})
    training_data.append({"class":"Nederlands", "sentence":"Zijn kraag stond overeind zoals de staart van een woeste kat."})
    training_data.append({"class":"Nederlands", "sentence":"Niemand kon zijn glimlach zien."})
    training_data.append({"class":"Nederlands", "sentence":"Ze heet Room, grauwde hij met de fluisterende stem van een moordenaar."})
    training_data.append({"class":"Nederlands", "sentence":"Het was de enige verklaring die hij de paparazzi gaf."})
    training_data.append({"class":"Nederlands", "sentence":"Diezelfde woorden vormden de volgende dag de kop boven het artikel op de voorpagina van alle grote dagbladen."})
    training_data.append({"class":"Nederlands", "sentence":"Het leek erop dat het die dag weer een beetje lichter werd op straat."})
    training_data.append({"class":"Nederlands", "sentence":"Een originele creatie van Sam Hudder."})

    # Engels
    training_data.append({"class":"Engels", "sentence":"transmitted in any form or by any means electronically, electrostatic magnetic tape or mechanically including photocopying, recording or by any information storage and retrieval system, without prior permission in writing from the author."})
    training_data.append({"class":"Engels", "sentence":"Although this is a fictional work, some locations, organisations and events are factual."})
    training_data.append({"class":"Engels", "sentence":"The characters and times in the story line are fictional - therefore, all resemblances to actual people present or past are purely coincidental."})
    training_data.append({"class":"Engels", "sentence":"Bringing Down The Firm Synopsis The great poet, Sufi, and philosopher, Rumi (1207) - in what is today Afghanistan, moulded mankind perfectly - coincidentally still fitting - in typical genius style, he managed to pour his thoughts into text."})
    training_data.append({"class":"Engels", "sentence":"We show our worth, by what we seek Prologue Shuffling the unforgiving world as an orphan of the system, is something only 'some' might understand, or make some sort of peace with."})
    training_data.append({"class":"Engels", "sentence":"But then."})
    training_data.append({"class":"Engels", "sentence":"making peace, is how the system slaves a mind into acceptance of our circumstances."})
    training_data.append({"class":"Engels", "sentence":"Looks like the storm is here to stay sir."})
    training_data.append({"class":"Engels", "sentence":"It is ironic that I'm bugging your partners? I thought I'd never do work for you sir Good evening Zach."})
    training_data.append({"class":"Engels", "sentence":"How much? It's on the house sir."})
    training_data.append({"class":"Engels", "sentence":"My payment will be information you have."})
    training_data.append({"class":"Engels", "sentence":"I'm sure your calculations will be correct."})
    training_data.append({"class":"Engels", "sentence":"Maybe a tip? A prediction if you may, sir? Gladly It's."})
    training_data.append({"class":"Engels", "sentence":"well I've listened to the convo's."})
    training_data.append({"class":"Engels", "sentence":"Where would you - had you been me, invested your money sir? Normally energy, food and communication."})
    training_data.append({"class":"Engels", "sentence":"First thing in the morning, take all your money out of anything my partners have invested in."})
    training_data.append({"class":"Engels", "sentence":"Car importers, tech, and the paper-mill Thank you sir."})
    training_data.append({"class":"Engels", "sentence":"The firm had amassed a fortune for the families they had served."})
    training_data.append({"class":"Engels", "sentence":"I for one, am going to miss all this."})
    training_data.append({"class":"Engels", "sentence":"Really I am."})
    training_data.append({"class":"Engels", "sentence":"Anything else sir? Yes, actually."})
    training_data.append({"class":"Engels", "sentence":"Can you load this on YouTube? I mean as a voice file."})
    training_data.append({"class":"Engels", "sentence":"It needs to look like one of the detectives had bugged my partners and done the career-killer move and uploaded it? I'm their IT guy sir."})
    training_data.append({"class":"Engels", "sentence":"Don't forget to get - your money needs to be out before 9 o'clock tomorrow."})
    training_data.append({"class":"Engels", "sentence":"Pack a large suitcase and take a break too I have one packed and in the boot sir."})
    training_data.append({"class":"Engels", "sentence":"I had a feeling you weren't going to stand for what they've done."})
    training_data.append({"class":"Engels", "sentence":"Just never thought you'd be the one."})
    training_data.append({"class":"Engels", "sentence":"I had some help."})
    training_data.append({"class":"Engels", "sentence":"Well talk later."})
    training_data.append({"class":"Engels", "sentence":"Who knows when."})
    training_data.append({"class":"Engels", "sentence":"I'm leaving in a few minutes None of my business sir."})
    training_data.append({"class":"Engels", "sentence":"But are you going to be far from here? Passing the police station briefly."})
    training_data.append({"class":"Engels", "sentence":"After that, who knows."})
    training_data.append({"class":"Engels", "sentence":"Wishing you well sir."})
    training_data.append({"class":"Engels", "sentence":"You're doing the right thing."})
    training_data.append({"class":"Engels", "sentence":"Take care And you."})
    training_data.append({"class":"Engels", "sentence":"By the way, the coffee guy."})
    training_data.append({"class":"Engels", "sentence":"thank you No idea what you're talking about sir."})
    training_data.append({"class":"Engels", "sentence":"Have a good night It was really nothing short of a blessing."})
    training_data.append({"class":"Engels", "sentence":"I was going to attend to 'unfinished' business myself."})
    training_data.append({"class":"Engels", "sentence":"But one has a name to uphold."})
    training_data.append({"class":"Engels", "sentence":"Besides my type of revenge is limited to short-term purposes."})
    training_data.append({"class":"Engels", "sentence":"You know, quick-glue squirted into car locks, so they can't oppose bail in time."})
    training_data.append({"class":"Engels", "sentence":"Gluing their wiper blades onto their windscreens on a rainy day, getting their credit card details and having ordered not more than one truck of quick drying concrete poured out over the outside of their driveways, things like that."})
    training_data.append({"class":"Engels", "sentence":"Never physical harm."})
    training_data.append({"class":"Engels", "sentence":"I used to think about getting physical."})
    training_data.append({"class":"Engels", "sentence":"Gosh, I even plan it."})
    training_data.append({"class":"Engels", "sentence":"But timing is everything."})
    training_data.append({"class":"Engels", "sentence":"If a cup of coffee could be life-changing, 'that' last cup, would have been IT for me."})
    training_data.append({"class":"Engels", "sentence":"The first two cups had been duelling with uncertainty."})
    training_data.append({"class":"Engels", "sentence":"Sorting out the finer details, if you want."})
    training_data.append({"class":"Engels", "sentence":"We had nine untouchable enemies, and there were two of us."})
    training_data.append({"class":"Engels", "sentence":"The man slowly poured a cup of house-brand coffee down his throat, left, had a cigarette on the pavement, and then strolled back to our table."})
    training_data.append({"class":"Engels", "sentence":"I don't know how some people do it."})
    training_data.append({"class":"Engels", "sentence":"Really."})
    training_data.append({"class":"Engels", "sentence":"I timed it."})
    training_data.append({"class":"Engels", "sentence":"It was nine minutes flat."})
    training_data.append({"class":"Engels", "sentence":"He said after."})
    training_data.append({"class":"Engels", "sentence":"Sorry."})
    training_data.append({"class":"Engels", "sentence":"I needed a minute for each Imagine what kind of psycho's hang out in coffee shops and book shops."})
    training_data.append({"class":"Engels", "sentence":"From what I've seen in all my years, you're safer in bar at 11 o'clock at night buying the leader of a notorious gang of bike thieves a beer."})
    training_data.append({"class":"Engels", "sentence":"They plan short-term."})
    training_data.append({"class":"Engels", "sentence":"The odd stabbing in the bathroom with a switch-blade, or accidental shot from a 38-special through the bonnet of your ride."})
    training_data.append({"class":"Engels", "sentence":"well those things are quick forgotten, and tomorrow they'll buy you a beer and let you wear one of their helmets while you down three Tequilas and tell attorney jokes."})
    training_data.append({"class":"Engels", "sentence":"They love attorney jokes."})
    training_data.append({"class":"Engels", "sentence":"A lot."})
    training_data.append({"class":"Engels", "sentence":"And I'm sufficiently in attorney jokes, to turn the tables and have them buy me enough - while I figure out who'd be the best candidate to slip a thousand green backs."})
    training_data.append({"class":"Engels", "sentence":"The car locks, or the wipers on the windscreen, were always dependent on the weather forecast."})
    training_data.append({"class":"Engels", "sentence":"But it goes without saying that the glue doesn't work by remote control."})
    training_data.append({"class":"Engels", "sentence":"I'm regressing."})
    training_data.append({"class":"Engels", "sentence":"I do that."})
    training_data.append({"class":"Engels", "sentence":"The judges hate me in Court for that."})
    training_data.append({"class":"Engels", "sentence":"Back to polite conversations you'll only hear, or overhear, in a dusty bookshop or a buzzing coffee shop."})
    training_data.append({"class":"Engels", "sentence":"I needed a minute for each That's all he said."})
    training_data.append({"class":"Engels", "sentence":"He had the waiter come over with the second cup of coffee."})
    training_data.append({"class":"Engels", "sentence":"We met again the next evening."})
    training_data.append({"class":"Engels", "sentence":"We would not meet again after that."})
    training_data.append({"class":"Engels", "sentence":"If you can get this key to the Captain, and get them to use the machine, then we have a deal."})
    training_data.append({"class":"Engels", "sentence":"As a token of my commitment I'll start on it tonight."})
    training_data.append({"class":"Engels", "sentence":"No refunds."})
    training_data.append({"class":"Engels", "sentence":"You'll wait at table eight."})
    training_data.append({"class":"Engels", "sentence":"We'll talk."})
    training_data.append({"class":"Engels", "sentence":"You decide on which one of them, and how."})
    training_data.append({"class":"Engels", "sentence":"How you want them."})
    training_data.append({"class":"Engels", "sentence":"swap the timely, with the eternal Done The next night."})
    training_data.append({"class":"Engels", "sentence":"Would you like warm milk or cold? And how do feel about sugar and cream? What the police would later listen to - till boredom had set in, would mean precisely nothing to them."})
    training_data.append({"class":"Engels", "sentence":"The repeated effects of the mentions, of things we associate with coffee? I'm still not sure how."})
    training_data.append({"class":"Engels", "sentence":"But I read in the news, that the man was spot on."})
    training_data.append({"class":"Engels", "sentence":"He'd hoped to have instigated an insistent demand for coffee from the express machine."})
    training_data.append({"class":"Engels", "sentence":"I'm not saying their 'own' coffee wasn't anything to write home to, about."})
    training_data.append({"class":"Engels", "sentence":"But if you know coffee like I do."})
    training_data.append({"class":"Engels", "sentence":"It wasn't."})
    training_data.append({"class":"Engels", "sentence":"Believe me."})
    training_data.append({"class":"Engels", "sentence":"The gigantic modern coffee contraption had been halfway down the hall, about ten feet from the men's bathrooms."})
    training_data.append({"class":"Engels", "sentence":"That's where the man had placed it."})

    # Duits
    training_data.append({"class":"Duits", "sentence":"Zweifle nie daran, dass eine kleine Gruppe engagierter Menschen die Welt verandern kann tatsachlich ist dies die einzige Art und Weise, in der die Welt jemals verandert wurde."})
    training_data.append({"class":"Duits", "sentence":"Margaret Mead Dieser Satz der Ethnologin Margaret Mead ist die beste Einleitung fur dieses Buch, weil er eines von Raphaels Lieblingszitaten und durchaus wahr ist."})
    training_data.append({"class":"Duits", "sentence":"Er spiegelt wider, wovon mein Mann und viele Aktivisten aus tiefstem Herzen uberzeugt sind."})
    training_data.append({"class":"Duits", "sentence":"Diese Zeilen sind mit unerschopflicher Liebe zum Leben geschrieben, mit einem enormen Willen dazu, etwas in der gegenwartigen Gesellschaft und im Miteinander zu verandern, alles mit einem radikalen Verantwortungsgefuhl."})
    training_data.append({"class":"Duits", "sentence":"Ich unterstutze Raphael bedingungslos bei seinem Geldstreik, der nichts weniger ist als ein Protest gegen das kapitalistische System, in dem wir leben, das von einem ganzheitlichen Blickwinkel aus gesehen ein System der Unterdruckung ist."})
    training_data.append({"class":"Duits", "sentence":"Dieses Buch, das sowohl eine Autobiografie als auch ein Reise- und Alltagsbericht ist, enthalt viele wertvolle Informationen Der ausdruckliche Verzicht auf das Geld soll wichtige und aktuelle Themen wie Lebensmittelverschwendung, virtuelles Wasser und die graue Energie beleuchten und okologische Methoden wie Veganismus, gemeinsamer Konsum, Postokonomie und viele andere vorstellen, um uns zu tiefem Nachdenken zu animieren und dazu, ein neues Paradigma oder formales organisatorisches Schema aufzubauen."})
    training_data.append({"class":"Duits", "sentence":"Seit Beginn des geldfreien Lebens im Januar 2010 haben sich viele Menschen inspirieren lassen und wir haben etwas in uns verandert, um somit auch etwas in der Welt ver- Vorwort 8 andern zu konnen."})
    training_data.append({"class":"Duits", "sentence":"Ich verspure Dankbarkeit fur die Arbeit von Raphael und ich liebe ihn seit dem ersten Tag, an dem ich ihm begegnete, weil er ein Mensch mit wunderbaren und soliden Prinzipien ist, der sich voll und ganz fur das Gemeinwohl einsetzt, ebenso weil er der integerste Mensch ist, den ich kenne, und wegen seiner enormen Fahigkeit zu lieben und das Gute in Menschen zu sehen."})
    training_data.append({"class":"Duits", "sentence":"Obwohl ich noch Geld benutze, ist mein Budget sehr klein."})
    training_data.append({"class":"Duits", "sentence":"Ansonsten leben wir ein Leben ohne Geld, indem wir es in Einklang bringen mit notwendigen Dingen wie Wohnung, Nahrungsmitteln und Kleidung, sowohl fur uns als auch fur unsere geliebte Tochter Alma -Lucia."})
    training_data.append({"class":"Duits", "sentence":"Wir empfinden den Verzicht auf Geld nicht als Einschrankung, sondern als etwas ganz Naturliches, und wir haben uns die Devise Weniger ist mehr auf eine praktische, ja, ich wurde auch sagen, auf eine spirituelle Weise zu eigen gemacht."})
    training_data.append({"class":"Duits", "sentence":"Ich erlebe es als eine Moglichkeit, ein einfaches, optimistisches Leben zu fuhren in respektvollem Einklang mit Mutter Erde, als eine Art und Weise, gewissenhaft und konsequent zu leben und dem Menschlichen den Vorrang zu geben."})
    training_data.append({"class":"Duits", "sentence":"Raphael verzichtet auf jegliche wirtschaftliche Ertrage, die mit diesem Buch erzielt werden."})
    training_data.append({"class":"Duits", "sentence":"Dieses Buch ist als E-Book kostenlos verfugbar."})
    training_data.append({"class":"Duits", "sentence":"An verschiedenen Stellen im ganzen Land werden mehr als 2000 Exemplare kostenlos vergeben."})
    training_data.append({"class":"Duits", "sentence":"Das Buch wurde auf bestem Recyclingpapier und mit veganem Klebstoff gedruckt."})
    training_data.append({"class":"Duits", "sentence":"Wir wurden uns freuen, wenn Du dieses Buch nicht behalten, sondern weiterverschenken wurdest."})
    training_data.append({"class":"Duits", "sentence":"Ich mochte Dir personlich danken, dass Du Dir die Zeit nehmen willst, um von Raphaels Beweggrunden zu erfahren, von seiner Geschichte, unserer Geschichte."})
    training_data.append({"class":"Duits", "sentence":"Du gibst dem, was wir als Familie tun, Sinn."})
    training_data.append({"class":"Duits", "sentence":"Du bist ein aktiver Bestandteil der Revolution."})
    training_data.append({"class":"Duits", "sentence":"Vielen Dank und viel Gluck."})
    training_data.append({"class":"Duits", "sentence":"Nieves Palmer Muntaner August 2013, Berlin 9 1."})
    training_data.append({"class":"Duits", "sentence":"Das Geschenk des Lebens Ich bin ein Mensch wie Du und Gast auf demselben Planet wie Du."})
    training_data.append({"class":"Duits", "sentence":"Meine Eltern schenkten mir vor 30 Jahren den Namen Raphael."})
    training_data.append({"class":"Duits", "sentence":"Schon, dass es Dich gibt, ich freue mich, dass Dir dieses Buch in die Hande gefallen ist."})
    training_data.append({"class":"Duits", "sentence":"Das ist sicherlich kein reiner Zufall, sondern vielmehr Schicksal."})
    training_data.append({"class":"Duits", "sentence":"Im dem Wort Schicksal steckt das Wort schicken, was fur mich bedeutet, dass es einen Grund und einen Sinn gibt, warum Du diese Zeilen liest."})
    training_data.append({"class":"Duits", "sentence":"Wie fur alles, was uns im Leben geschickt wird."})
    training_data.append({"class":"Duits", "sentence":"Oft wird uns im Leben die Kausalkette und innere Logik, warum etwas zu einem bestimmten Zeitpunkt passiert, erst spater voll bewusst."})
    training_data.append({"class":"Duits", "sentence":"So geschah es auch, als ich an einem schonen Sommertag im August 1983 das Licht der Welt erblickte."})
    training_data.append({"class":"Duits", "sentence":"Mein Gluck auf Erden begann mit dem Geschenk des Lebens."})
    training_data.append({"class":"Duits", "sentence":"Auch heute noch konnte ich mir keine besseren Eltern vorstellen, denn sie gaben mir von Anfang an unendliche Liebe, Vertrauen und Zuneigung."})
    training_data.append({"class":"Duits", "sentence":"Als Familie waren wir nicht immer alle der gleichen Meinung, aber genau das war es, was unser Familiensein so lebhaft machte."})
    training_data.append({"class":"Duits", "sentence":"Die Vielfalt an Meinungen, Denkweisen und Ansichten bereicherten mich in meiner Wesensfindung."})
    training_data.append({"class":"Duits", "sentence":"Das Leben ist eine unendliche Aneinanderknupfung von Geschenken, sie alle sind vollig kostenlos."})
    training_data.append({"class":"Duits", "sentence":"Und noch viel besser Sie sind mit keiner irgendwie gearteten Erwartungshaltung verbunden und das macht die Gabe des Lebens so besonders lebens- und liebenswert."})
    training_data.append({"class":"Duits", "sentence":"Sie ist vollkommen frei von jeglichem konditioniertem Verhalten, ohne Vorurteile, storende Gedanken oder angste."})
    training_data.append({"class":"Duits", "sentence":"Beklommenheit, Zukunftssorgen und Dingen nachzutrauern gibt es in der Welt der Neugeborenen nicht."})
    training_data.append({"class":"Duits", "sentence":"Die gesamte Aufmerksamkeit und das vol- Das Geschenk des Lebens 10 le Bewusstsein sind dem Moment gewidmet, und zwar ohne dass sie dafur zuvor irgendeine Technik oder Theorie erlernen mussten."})
    training_data.append({"class":"Duits", "sentence":"Es ist ihr ureigener Seinszustand."})
    training_data.append({"class":"Duits", "sentence":"Das Leben auf diesem einmaligen Planeten wird uns geschenkt wie die Luft, die wir atmen, die Natur, die uns am Leben halt, und das Wasser, das uns vitalisiert."})
    training_data.append({"class":"Duits", "sentence":"Wir sind Teil eines einzigartigen okosystems und zusammen mit Millionen von Spezies besitzen wir das Privileg, diese so einzigartige und lebensspendende Mutter Erde zu teilen, mit unserem Sein zu durchdringen und zu wirken."})
    training_data.append({"class":"Duits", "sentence":"Der Blaue Planet bietet allen seinen Gasten genug, um in Hulle und Fulle zu gedeihen, es gibt nichts, woran es mangelt."})
    training_data.append({"class":"Duits", "sentence":"Schon als kleines Kind konnte ich nicht begreifen, dass es so viel Ungerechtigkeit und Leid gibt, obwohl wir uns doch alle im Herzen nach Frieden und Liebe sehnen."})
    training_data.append({"class":"Duits", "sentence":"Ich fragte mich immer, wieso es uns so gut geht und wir alles haben und gleichzeitig andere Menschen tagtaglich an Hunger leiden und sterben mussen."})
    training_data.append({"class":"Duits", "sentence":"Als ich zwolf Jahre alt war, begann ich mein eigenes Geld zu verdienen."})
    training_data.append({"class":"Duits", "sentence":"Schnell entwickelte ich einen Bezug zum Geld und zu der Arbeitsleistung, die ich erbringen musste, um mir mit dem Erwirtschafteten Produkte und Dienstleistungen kaufen zu konnen."})
    training_data.append({"class":"Duits", "sentence":"Ich spurte die finanzielle Unabhangigkeit, die mir die Freiheit bot, zu kaufen, was ich begehrte."})
    training_data.append({"class":"Duits", "sentence":"Ich verstand, dass, wenn ich meine Zeit in Nebenjobs investierte, ich damit die Moglichkeit bekam, mir Waren oder Vergnugen leisten zu konnen, ohne Dritten gegenuber Rechenschaft"})

    # Frans
    training_data.append({"class":"Frans", "sentence":"venez donc  vous nous raconterez ce qui vous est arrive."})
    training_data.append({"class":"Frans", "sentence":"Il ne m'est rien arrive du tout je n'ai rien a 25 raconter, ma cousine."})
    training_data.append({"class":"Frans", "sentence":"Si j'en crois un mot, je veux bien etre pendue."})
    training_data.append({"class":"Frans", "sentence":"Va, va t'habiller  nous nous passerons bien de toi, mon garcon."})
    training_data.append({"class":"Frans", "sentence":"Je vais prendre ton jeu au croquet et sois tranquille, je te gagnerai ta partie."})
    training_data.append({"class":"Frans", "sentence":"Georges, etonne et ennuye, obeit pourtant a la bonne, qui l'appelait."})
    training_data.append({"class":"Frans", "sentence":"Pendant sa courte absence, Mlle Primerose ne perdit pas son temps  en jouant au croquet aussi lourdement et maladroitement que le faisait supposer sa grosse taille, elle questionna habilement Genevieve et apprit ainsi ce qui s'etait passe, excepte le mecontentement de  Dormere et le vilain role qu'avait joue Georges en presence de son pere."})
    training_data.append({"class":"Frans", "sentence":"Quand Georges revint, elle lui remit son maillet de croquet."})
    training_data.append({"class":"Frans", "sentence":"Je n'ai pas eu de bonheur, mon ami  j'ai perdu votre partie."})
    training_data.append({"class":"Frans", "sentence":"Mais j'ai gagne a votre absence de savoir toute votre aventure du bois et 26 des fraises."})
    training_data.append({"class":"Frans", "sentence":"Georges devint tres rouge  il lanca un regard furieux a la pauvre Genevieve."})
    training_data.append({"class":"Frans", "sentence":"Mlle Primerose retourna au salon, pendant que les enfants recommencaient une partie de croquet."})
    training_data.append({"class":"Frans", "sentence":"Mon cher cousin, dit-elle en entrant au salon, je viens justifier le pauvre Georges  je sais toute l'histoire il ne merite pas d'etre gronde pour avoir sali ses habits  au contraire,"})
    training_data.append({"class":"Frans", "sentence":"il merite des eloges, car c'est en secourant Genevieve, qui ne pouvait sortir des ronces ou elle etait imprudemment entree, qu'il s'est verdi a l'etat de gresset. "})
    training_data.append({"class":"Frans", "sentence":"Je le sais, ma cousine, et je n'ai pas gronde Georges."})
    training_data.append({"class":"Frans", "sentence":"qui avez-vous gronde, car vous avez gronde quelqu'un ?"})
    training_data.append({"class":"Frans", "sentence":"J'ai gronde Genevieve, qui meritait d'etre 27 grondee."})
    training_data.append({"class":"Frans", "sentence":"Qu'a-t-elle donc fait, la pauvre fille ?"})
    training_data.append({"class":"Frans", "sentence":"C'est elle qui a pousse, presque oblige Georges a entrer dans le bois pour manger des fraises, comme si elle n'en avait pas assez dans le jardin, et plus tard c'est elle qui a voulu revenir au travers des ronces."})
    training_data.append({"class":"Frans", "sentence":"Qu'est-ce que vous dites donc, mon pauvre cousin  c'est au contraire elle qui ne voulait pas, et c'est Georges qui l'a voulu."})
    training_data.append({"class":"Frans", "sentence":"Je vois que vous n'etes pas bien informe de ce qui se passe chez vous."})
    training_data.append({"class":"Frans", "sentence":"Moi qui suis ici depuis une demi-heure, je suis plus au courant que vous."})
    training_data.append({"class":"Frans", "sentence":"Me permettez-vous de vous demander, ma cousine, par qui vous avez ete si bien informee ?"})
    training_data.append({"class":"Frans", "sentence":"Par Genevieve elle-meme."})
    training_data.append({"class":"Frans", "sentence":"Je ne m'etonne pas alors que l'histoire vous ait ete contee de cette maniere  Genevieve a toujours le triste talent de tout rejeter sur Georges."})
    training_data.append({"class":"Frans", "sentence":"Mais, au contraire  elle a parle de Georges avec eloge, avec grand eloge, et si je vous en ai parle, c'est qu'elle m'avait avoue que vous n'etiez pas content et je croyais que c'etait Georges que vous aviez gronde."})
    training_data.append({"class":"Frans", "sentence":"Et par le fait il le meritait un peu, quoi qu'en dise Genevieve."})
    training_data.append({"class":"Frans", "sentence":"Dormere, un peu surpris, ne repondit pas, pour ne pas accuser Georges, dont il comprit enfin le silence."})
    training_data.append({"class":"Frans", "sentence":"Mlle Primerose retourna pres des enfants pour tacher de mieux eclaircir l'affaire, qui lui semblait un peu brouillee du cote de Georges."})
    training_data.append({"class":"Frans", "sentence":"Elle trouva Genevieve en larmes  Georges 29 boudait dans un coin  Louis et Helene cherchaient a consoler Genevieve."})
    training_data.append({"class":"Frans", "sentence":"Eh bien ! eh bien ! qu'y a-t-il encore ? qu'estce que c'est ? Ce n'est rien, ma cousine  je me suis fait mal a la jambe, repondit Genevieve en essuyant ses larmes."})
    training_data.append({"class":"Frans", "sentence":"Et pourquoi Georges boude-t-il tout seul pres du mur ? HeLeNE."})
    training_data.append({"class":"Frans", "sentence":"Parce que, Louis et moi, nous lui avons dit qu'il etait mechant et que nous ne voulions plus jouer avec lui."})
    training_data.append({"class":"Frans", "sentence":"Pourquoi lui avez-vous dit cela ? LOUIS."})
    training_data.append({"class":"Frans", "sentence":"Parce qu'apres avoir dit beaucoup de choses 30 desagreables a la pauvre Genevieve, qui ne lui repondait rien, il lui a donne un grand coup de maillet dans les jambes."})
    training_data.append({"class":"Frans", "sentence":"Helene et moi, nous nous sommes faches  nous avons chasse Georges et nous sommes revenus consoler la pauvre Genevieve qui pleurait."})
    training_data.append({"class":"Frans", "sentence":"Mechant garcon, va ! Tu meriterais que j'aille raconter tout cela a ton pere, qui te croit si bon."})
    training_data.append({"class":"Frans", "sentence":"Non, non, ma cousine, ne dites rien a mon oncle il punirait le pauvre Georges."})
    training_data.append({"class":"Frans", "sentence":"Punir Georges ! ton oncle ! Laisse donc ! il gronderait a peine."})
    training_data.append({"class":"Frans", "sentence":"Et puis, ma cousine, Georges n'a pas fait expres de me taper."})
    training_data.append({"class":"Frans", "sentence":"J'etais trop pres de sa boule, et il m'a attrape la jambe au lieu de la boule."})

    # Zweeds
    training_data.append({"class":"Zweeds", "sentence":"Klcka pa det alternatv som du anser vara ratt  menngarna nedan. Det ar bara ett av alternatven som ar ratt  varje menng."})
    training_data.append({"class":"Zweeds", "sentence":"Aradne rullade ut en ulltrad for att hjalpa Teseus ar ulltrad Neutrum Reale "})
    training_data.append({"class":"Zweeds", "sentence":"Tjuren hade tagt Teseus tll fanga ar Tjuren Bestamd form plural Obestamd form sngular Obestamd form plural Bestamd form sngular"})
    training_data.append({"class":"Zweeds", "sentence":"Mkael har sjungt  kyrkokoren under manga ar ar har sjungt Presens Perfekt mperfekt Pluskvamperfekt"})
    training_data.append({"class":"Zweeds", "sentence":"Jag hade skrvt halva brevet, nar strommen forsvann och datorn slocknade ar hade skrvt Presens Perfekt mperfekt Pluskvamperfekt"})
    training_data.append({"class":"Zweeds", "sentence":"Vem har lagt rabarber pa mn hatt? ar lagt Presens partcp nfntv Supnum mperfekt"})
    training_data.append({"class":"Zweeds", "sentence":"Huvudverbet  V har nte velat stora mamma hennes arbete ar har velat stora"})
    training_data.append({"class":"Zweeds", "sentence":"Rksdagen oppnas av kungen varje ar ar oppnas Passv form Aktv form Reflexv form"})
    training_data.append({"class":"Zweeds", "sentence":"Kan du hjalpa mg med den har uppgften? ar hjalpa Passv form Aktv form Reflexv form"})
    training_data.append({"class":"Zweeds", "sentence":"Aradne var modgare an Teseus ar modgare Komparatv Superlatv Postv"})
    training_data.append({"class":"Zweeds", "sentence":"Herakles ar den mest fascnerande gestalt jag vet ar den mest fascnerande Postv Komparatv Superlatv"})
    training_data.append({"class":"Zweeds", "sentence":"V hade en ovanlgt lugn seglats tll aland ar ovanlgt Adjektv Verb Adverb Substantv"})
    training_data.append({"class":"Zweeds", "sentence":"Maste du alltd svara sa spydgt? ar spydgt Preposton Konjunkton Adjektv Adverb"})
    training_data.append({"class":"Zweeds", "sentence":"Polsen sag henne lamna baten tllsammans med en man ar henne Relatvt pronomen Personlgt pronomen Possessvt pronomen Reflexvt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Lna kammar sg en halvtmme varje morgon ar sg Personlgt pronomen Demonstratvt pronomen Possessvt pronomen Reflexvt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"V fck nget kvtto nar v betalade, vlket forvanade oss ar vlket Relatvt pronomen Determnatvt pronomen Demonstratvt pronomen nterrogatvt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"V handlar nte av de forsaljare som nte lamnar kvtto ar de Relatvt pronomen Determnatvt pronomen Personlgt pronomen ndefnt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Man kan nte rakna med att fa nagot grats ar man nterrogatvt pronomen Determnatvt pronomen Personlgt pronomen ndefnt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Expedten fragade vlken storlek jag vlle ha pa studentmossan ar vlken Relatvt pronomen Determnatvt pronomen nterrogatvt pronomen ndefnt pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Eftersom ngen vll skrva protokoll, far jag val gora det sjalv ar eftersom Preposton Konjunkton Adverb Pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Utan att tveka ett ogonblck kastade Ronne sg  vattnet ar utan Preposton nterjekton Konjunkton Pronomen"})
    training_data.append({"class":"Zweeds", "sentence":"Efter talet delade kungen ut prset tll forfattaren ar kungen Predkat Ackusatvobjekt Subjekt Datvobjekt"})
    training_data.append({"class":"Zweeds", "sentence":"Flera av mna gamla elever har last sprak pa unverstetet ar har last Subjekt Datvobjekt Adverbal Predkat"})
    training_data.append({"class":"Zweeds", "sentence":"Expedten vsade kunden skorna ar skorna Predkatsfyllnad Ackusatvobjekt Subjekt Datvobjekt"})
    training_data.append({"class":"Zweeds", "sentence":"Vem gav n pengarna? ar Vem Predkat Ackusatvobjekt Subjekt Datvobjekt "})
    training_data.append({"class":"Zweeds", "sentence":"Motet beslutade att utse Stefan tll ordforande ar ordforande Predkatsfyllnad Ackusatvobjekt Subjekt Datvobjekt"})
    training_data.append({"class":"Zweeds", "sentence":"Det ar osakert vem som kommer att vnna nasta val ar osakert Ackusatvobjekt Adverbal Attrbut Predkatsfyllnad"})
    training_data.append({"class":"Zweeds", "sentence":"Tavlan pa vaggen har malats av Pcasso ar pa vaggen Apposton Adverbal Attrbut Predkatsfyllnad"})
    training_data.append({"class":"Zweeds", "sentence":"Mannens forvrrade upptradande skramde bort manga mannskor ar Mannens Attrbut Subjekt Adverbal  Predkatsfyllnad"})
    training_data.append({"class":"Zweeds", "sentence":"V kommer trolgen att flytta tll landet redan  maj ar  maj Attrbut Subjekt Adverbal Predkatsfyllnad"})
    training_data.append({"class":"Zweeds", "sentence":"For att komma tll skolan maste jag byta buss tre ganger ar tre ganger Attrbut Adverbal Ackusatvobjekt Subjekt"})
    training_data.append({"class":"Zweeds", "sentence":"Advokaten undrade om hans klent talade sannng ar den understrukna satsen ett exempel pa en Relatv bsats ndrekt fragesats Huvudsats"})
    training_data.append({"class":"Zweeds", "sentence":"Eftersom v kom for sent tll flygplatsen, mssade v planet ar den understrukna satsen en Huvudsats Konjunktonsbsats Relatv bsats"})
    training_data.append({"class":"Zweeds", "sentence":"vlken av de understrukna satserna ar ordfoljden omvand Efter ungefar fem mnuter var alla samlade. Ordforanden forklarade motet oppnat. Han fragade om nagon var vllg att skrva protokoll. Sara hade td att ata sg uppdraget."})
    training_data.append({"class":"Zweeds", "sentence":"vlken av foljande satser ar ordfoljden rak Pa fjarden lag sen blank och nbjudande. Sa hade den legat sedan langt fore jul. Fjarden var formodlgen bottenfrusen. Trots mn skrack for sar vagade jag mg ut. "})
    training_data.append({"class":"Zweeds", "sentence":"Swedex ar ett unikt, internationellt gangbart certifikatstest i svenska som frammande sprak framtaget av Folkuniversitetet."})
    training_data.append({"class":"Zweeds", "sentence":"Testet kan tas av alla som inte har svenska som modersmal och relaterar till Gemensam europeisk referensram for sprak, Europaradets nivaskala for sprakinlarning."})
    training_data.append({"class":"Zweeds", "sentence":"Fran 2011 kan man ta testet pa tre olika nivaer A2, B1 och B2. Swedex kan tas oberoende av hur man har lart sig svenska och ar erkant av Svenska institutet."})
    training_data.append({"class":"Zweeds", "sentence":"Swedex testar praktiskt anvandbara kunskaper inom alla sprakliga fardigheter tala, lasa, hora och skriva."})
    training_data.append({"class":"Zweeds", "sentence":"Ett Swedexcertifikat ar en vardehandling som dokumenterar denna fardighet och oppnar darfor for bade rattvisare bedomning vid rekrytering och kvalitetssakring inom manga skilda verksamheter."})
    training_data.append({"class":"Zweeds", "sentence":"ar ett internationellt test i svenska som frammande sprak ar ett spraktest erkant av Svenska institutet ar ett EU-projekt inom programmet SOCRATES lingua II"})
    training_data.append({"class":"Zweeds", "sentence":"testar praktiskt anvandbara kunskaper i svenska testar alla sprakliga fardigheter relaterar till Gemensam europeisk referensram for sprak finns pa tre nivaer A2, B1 och B2"})
    training_data.append({"class":"Zweeds", "sentence":"kan tas bade i och utanfor Sverige, pa 92 orter i 32 lander ar ett fristaende test som kan tas oavsett hur man lart sig svenska"})

    # Italiaans
    training_data.append({"class":"Italiaans", "sentence":"Un delitto in Piazza del Campo rischia di rovinare l'atmosfera gioiosa del Palio di Siena. L'assassino e davvero un personaggio della nobilta senese come fanno pensare alcuni indizi "})
    training_data.append({"class":"Italiaans", "sentence":"Saranno le indagini di un intraprendente giornalista in trasferta a Siena per scrivere un reportage sul palio a svelare tempestivamente l'identita del colpevole. "})
    training_data.append({"class":"Italiaans", "sentence":"La giovane Carolina sogna di lavorare, alla fine degli studi, in un grande hotel. Ma un giorno Valeria conosce Marco e da quel momento la sua vita subisce dei profondi cambiamenti. "})
    training_data.append({"class":"Italiaans", "sentence":"Il suo desiderio si avvera quando lo zio Giorgio, famosissimo cuoco in un albergo di lusso sul lago di como, le propone di passare l'estate lavorando e facendo pratica al Grand Hotel du Lac."})
    training_data.append({"class":"Italiaans", "sentence":"Carolina e entusiastica Finalmente una vacanza senza i soliti amici, senza i soliti posti, senza le solite cose Ma l'hotel nasconde un pericolo che mettera a rischio la sua vita "})
    training_data.append({"class":"Italiaans", "sentence":"Nella Lombardia del XVII secolo, tra guerre, carestie e pestilenze, il matrimonio tra Renzo e Lucia viene ostacolato in tutti i modi da un dispotico signore locale. "})
    training_data.append({"class":"Italiaans", "sentence":"L'adattamento di questo classico della letteratura italiana, per studenti di livello avanzato, e corredato da numerose attivita ed e arricchito da interessanti rubriche di civilta."})
    training_data.append({"class":"Italiaans", "sentence":"Il lettore avra cosi informazioni non solo sulla Milano del passato e del giorno d'oggi, ma anche su alcune tradizioni ed elementi del costume italiano. "})
    training_data.append({"class":"Italiaans", "sentence":"Veronica e Massimo sono molto diversi lei una donna d'affari, lui un artista. Eppure si incontrano e si amano. Quando pero Massimo le chiede di sposarlo, Veronica lo lascia. "})
    training_data.append({"class":"Italiaans", "sentence":"Lui, che comunque non vuole rassegnarsi ed ha la sensazione che Veronica gli nasconda qualcosa, comincia a indagare sul misterioso passato di lei"})
    training_data.append({"class":"Italiaans", "sentence":"Una storia appassionante e velata di mistero, un'avventura che accompagnera il lettore attraverso il nord Italia, dalla metropoli di Milano alla riviera ligure. "})
    training_data.append({"class":"Italiaans", "sentence":"Un mistero si nasconde nella vita di Valeria, li nella casa sulla scogliera. In paese si dice che, di notte, in quella casa si sentono grida e pianti e si vedono delle luci che si accendono e si spengono."})
    training_data.append({"class":"Italiaans", "sentence":"Come puo un tranquillo soggiorno in Italia trasformarsi in una vera e propria avventura e quello che succede ad Anna, una studentessa tedesca arrivata a Bergamo per perfezionare il suo italiano."})
    training_data.append({"class":"Italiaans", "sentence":"Un giorno trova nella sua camera il diario di Luisa, linquilina precedente lo sfoglia e scopre una pagina davvero inquietante Curiosa, Anna inizia ad indagare per risolvere il mistero con laiuto di un amico."})
    training_data.append({"class":"Italiaans", "sentence":"Signorina De Lorenzi, lei e sospettata dell'assassinio di Irene Pavlovich. "})
    training_data.append({"class":"Italiaans", "sentence":"La prima ballerina e stata uccisa poco prima dello spettacolo ed Eleonora, che l'ha sostituita, e chiaramente l'indiziata numero uno."})
    training_data.append({"class":"Italiaans", "sentence":"I sogni, il recente successo, la carriera tutta la sua vita rischia di essere rovinata per sempre. "})
    training_data.append({"class":"Italiaans", "sentence":"Sullo sfondo di una Milano autunnale, il commissario Bonardi conduce un'indagine complessa, perseguitato dalle note di una fuga di Bach. Eleonora e colpevole o innocente "})
    training_data.append({"class":"Italiaans", "sentence":"Enrico torna nella sua casa tra le montagne del Trentino Alto Adige. Non vede lora di incontrare il suo vecchio amico, il signor Barbarano, un chimico in pensione."})
    training_data.append({"class":"Italiaans", "sentence":"Ma il suo amico e sparito, ed Enrico scopre che e stato rapito. Ma da chi e perche Con laiuto di Camilla comincia a indagare."})
    training_data.append({"class":"Italiaans", "sentence":"Un racconto pieno di suspense e di colpi di scena un autentico giallo con un pizzico di sentimento"})
    training_data.append({"class":"Italiaans", "sentence":"Fabrizio e un uomo di successo dirigente in una grande societa, una bella moglie, dei figli adorabili e un caro amico, Bruno,"})
    training_data.append({"class":"Italiaans", "sentence":"altrettanto fortunato e in carriera, con il quale condividere giornate allegre e splendidi ricordi. Ma un giorno limprovvisa scomparsa di Bruno rompe"})
    training_data.append({"class":"Italiaans", "sentence":"lincantesimo della sua esistenza felice quanto, forse, illusoria. Bruno si e davvero suicidato come sostiene la polizia Era davvero un uomo realizzato"})
    training_data.append({"class":"Italiaans", "sentence":"Alcune scoperte veramente inaspettate costringono Fabrizio ad ammettere di non conoscere per nulla il suo migliore amico."})
    training_data.append({"class":"Italiaans", "sentence":"L'associazione culturale Bella Italia organizza per gli studenti stranieri una caccia al tesoro con tappe a Firenze, Napoli, Venezia,"})
    training_data.append({"class":"Italiaans", "sentence":"Siena, Milano, Agrigento. Quale migliore occasione per Mark, studente americano in Italia, di conoscere la penisola "})
    training_data.append({"class":"Italiaans", "sentence":"Accompagnatelo nella sua ricerca! Aiutatelo ad interpretare correttamente i messaggi che gli indicano il giusto percorso, scoprite"})
    training_data.append({"class":"Italiaans", "sentence":"con lui luoghi affascinanti e gustatevi le atmosfere, i paesaggi, le tradizioni offerti dalla splendida Italia! "})
    training_data.append({"class":"Italiaans", "sentence":"Dal diario di Valentina una storia damore che non conosce tempo.Una ragazza ricca e un po' snob e un giovane di umile famiglia, ma affascinante, si incontrano, si conoscono, si amano."})
    training_data.append({"class":"Italiaans", "sentence":"Dalla collezione privata di un importante uomo daffari spariscono alcune opere darte. Il proprietario sospetta di sua moglie e si rivolge ad unagenzia investigativa che incarica Ettore Bonetti di risolvere il caso."})
    training_data.append({"class":"Italiaans", "sentence":"Il giovane ed affascinante detective dovra raggiungere la donna in una pittoresca e deliziosa localita di mare vicino a Venezia, pedinarla e scoprire se e davvero responsabile del furto."})
    training_data.append({"class":"Italiaans", "sentence":"Durante la sua missione il simpatico protagonista fara piacevoli incontri e affrontera situazioni divertenti, strane e pericolose."})
    training_data.append({"class":"Italiaans", "sentence":"Daniele suona la chitarra e sogna di far parte di un gruppo musicale. Il suo sogno si avvera quando conosce Gianni, che gli propone di suonare con lui e i suoi amici."})
    training_data.append({"class":"Italiaans", "sentence":"Tra problemi e storie damore, i ragazzi si preparano a partecipare a un grande concerto, unoccasione unica per farsi conoscere e magari, chissa"})
    training_data.append({"class":"Italiaans", "sentence":"Storia e leggenda si intrecciano e addirittura il passato sembra rivivere nel presente. Fatevi guidare, come i protagonisti di questa storia, tra i luoghi suggestivi di una delle pi affascinanti citta italiane Venezia! "})
    training_data.append({"class":"Italiaans", "sentence":"Scoprirete l'atmosfera magica e fantastica che si respira in questa citta, dove il tempo sembra davvero essersi fermato! "})
    training_data.append({"class":"Italiaans", "sentence":"Ogni capitolo e arricchito da un'interessante rubrica, Curiosita veneziane, grazie alla quale il lettore potra conoscere le ricette tipiche, i palazzi pi suggestivi, i ponti simbolo della citta, ecc. "})
    training_data.append({"class":"Italiaans", "sentence":"Alla scoperta delle proprie origini, Laurent intraprende un viaggio che inizia a Parigi e, passando per Firenze, Roma e Positano, lo condurra in alcune delle pi belle citta d'Italia. "})
    training_data.append({"class":"Italiaans", "sentence":"Quest'esperienza e l'incontro con Luigi, un lontano parente, permetteranno a Laurent di ritrovare un legame profondo con la sua famiglia, ma anche con quei colori, sapori e odori tipicamente italiani. "})
       
    for line in training_data:
        line['sentence'] = line['sentence'].strip().decode("ascii", "ignore").encode("ascii")
        line['sentence'] = line['sentence'].lower()
        if line['sentence'] == "":continue
    
    return training_data

